### ISSUE TITLE
Security: Open DNS Resolver

### ISSUE THREAD

**Issue by shimuldn** [olimpo88/PyDDNS#10]
I was playing with PyDDNS a bit.
The IP address of the PyDDNS server or the domain pointed on work as Open DNS Resolver!

DDNS needs port 53 to work right?

How can i safeguard the PyDDNS server from being an Open DNS Resolver?

**Comment by olimpo88** [comment]
All DNS servers must be with port 53 open and it is public, this is a must, because otherwise the rest of the world servers cannot communicate with it.

An open DNS server is one that responds to anyone's DNS requests for anything. PyDDNS is  not **Open**
You can check it with the following command:

dig google.com @yourip

**Comment by shimuldn** [comment]
You're correct, PyDDNS is not `Open DNS Resolver`.

I did some bad changes, Sorry.
