### ISSUE TITLE
nsupdate.info

### ISSUE THREAD

**Issue by stokito** [olimpo88/PyDDNS#34]
From sources I see that the PyDNS just calls by DynDNS2 protocol the davd/docker-ddns
https://github.com/olimpo88/PyDDNS/blob/master/appdata/pyddns/pyddns/views.py#L381=

But internally it just executes a command `nsupdate` for the BIND (or any other DNS server that supports RFC 2136 
https://github.com/dprandzioch/docker-ddns/blob/5c39bf8a810bf12ed81b16502ecc5821e48a859f/rest-api/main.go#L118=
Here it just executes nsupdate command from bind-client package (or kresd)

Technically speaking this can be easily added to the PyDDNS so users may avoid the unneeded step.

Another question: there is already exists a very similar UI and server for DDNS which is also written in Django https://github.com/nsupdate-info/nsupdate.info
It already supports the nsupdate execution. 
Is it possible to merge this two projects? Or please tell me which is better to use.

**Comment by olimpo88** [comment]
Hello, thanks for writing @stokito, I do not understand very well what you need.

The project started because I used the dprandzioch project: https://github.com/dprandzioch/docker-ddns

This project is fantastic for administrators, but it wasn't very friendly for end users without much knowledge,  that's why I put together a web interface.

I'm currently working on other projects and only maintain this one when security updates need to be applied, but it's open source feel free to come up with ideas or code if it helps another project. Or ask me if you need help, I have no problem collaborating.

**Comment by stokito** [comment]
thank you
